### ISSUE TITLE
能收到推送，但 Receiver 并不能接收到信息

### ISSUE THREAD

**Issue by nukc** [MEIZUPUSH/PushDemo#11]
在新的推送平台推送信息，手机能接收到，并 notification 显示了。
但是 Receiver 并不能接受到回调信息。
onRegisterStatus , onSubAliasStatus 和 onNotificationClicked 倒是有回调

**Comment by nukc** [comment]
型号： pro6
flyme 6.0.2.0A

**Comment by nukc** [comment]
推送成功后，看到如下 log
```java
E/Parcel: Class not found when unmarshalling: com.meizu.cloud.pushsdk.handler.MessageV3
                                         java.lang.ClassNotFoundException: com.meizu.cloud.pushsdk.handler.MessageV3
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.Class.forName(Class.java:324)
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2383)
                                             at android.os.Parcel.readParcelable(Parcel.java:2337)
                                             at android.os.Parcel.readValue(Parcel.java:2243)
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2592)
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                             at android.os.BaseBundle.keySet(BaseBundle.java:322)
                                             at com.wandoujia.nisdk.core.util.IntentUtil.getExtrasSafe(IntentUtil.java:128)
                                             at com.wandoujia.nisdk.core.model.converter.SystemNotificationConverter.toIntentPackage(SystemNotificationConverter.java:243)
                                             at com.wandoujia.nisdk.core.model.converter.SystemNotificationConverter.toPendingIntentPackage(SystemNotificationConverter.java:215)
                                             at com.wandoujia.nisdk.core.model.converter.SystemNotificationConverter.convert(SystemNotificationConverter.java:49)
                                             at com.wandoujia.nisdk.core.NIFilter.filter(NIFilter.java:92)
                                             at com.meizu.notification.NisNotificationFilterImpl.filter(NisNotificationFilterImpl.java:122)
                                             at com.meizu.notification.FlymeNotificationFilterService$2.interceptNotification(FlymeNotificationFilterService.java:115)
                                             at meizu.notification.INotificationFilterService$Stub.onTransact(INotificationFilterService.java:57)
                                             at android.os.Binder.execTransact(Binder.java:462)
                                          Caused by: java.lang.ClassNotFoundException: com.meizu.cloud.pushsdk.handler.MessageV3
                                             at java.lang.Class.classForName(Native Method)
                                             at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                             at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                             at java.lang.Class.classForName(Native Method) 
                                             at java.lang.Class.forName(Class.java:324) 
                                             at android.os.Parcel.readParcelableCreator(Parcel.java:2383) 
                                             at android.os.Parcel.readParcelable(Parcel.java:2337) 
                                             at android.os.Parcel.readValue(Parcel.java:2243) 
                                             at android.os.Parcel.readArrayMapInternal(Parcel.java:2592) 
                                             at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                             at android.os.BaseBundle.keySet(BaseBundle.java:322) 
                                             at com.wandoujia.nisdk.core.util.IntentUtil.getExtrasSafe(IntentUtil.java:128) 
                                             at com.wandoujia.nisdk.core.model.converter.SystemNotificationConverter.toIntentPackage(SystemNotificationConverter.java:243) 
                                             at com.wandoujia.nisdk.core.model.converter.SystemNotificationConverter.toPendingIntentPackage(SystemNotificationConverter.java:215) 
                                             at com.wandoujia.nisdk.core.model.converter.SystemNotificationConverter.convert(SystemNotificationConverter.java:49) 
                                             at com.wandoujia.nisdk.core.NIFilter.filter(NIFilter.java:92) 
                                             at com.meizu.notification.NisNotificationFilterImpl.filter(NisNotificationFilterImpl.java:122) 
                                             at com.meizu.notification.FlymeNotificationFilterService$2.interceptNotification(FlymeNotificationFilterService.java:115) 
                                             at meizu.notification.INotificationFilterService$Stub.onTransact(INotificationFilterService.java:57) 
                                             at android.os.Binder.execTransact(Binder.java:462) 
                                          Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by comsince** [comment]
这个是系统通知报的错，升级固件应该能解决

**Comment by comsince** [comment]
你说的回调应该是通知栏到达回调吧，onNotificationArrived 这个回调在基于android6.0上不回调！
