### ISSUE TITLE
3.5.1 版本出现 SharedPreference 的 ConcurrentModificationException

### ISSUE THREAD

**Issue by hamberluo** [MEIZUPUSH/PushDemo#17]
仅限魅族 Android 5.1 系统

**Comment by comsince** [comment]
有没有完整堆栈信息

**Comment by hamberluo** [comment]
堆栈只能抓到这里
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
       at java.util.HashMap$KeyIterator.next(HashMap.java:814)
       at com.android.internal.util.XmlUtils.writeSetXml(XmlUtils.java:350)
       at com.android.internal.util.XmlUtils.writeValueXml(XmlUtils.java:688)
       at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:295)
       at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:264)
       at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:230)
       at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:187)
       at android.app.SharedPreferencesImpl.writeToFile(SharedPreferencesImpl.java:597)
       at android.app.SharedPreferencesImpl.access$800(SharedPreferencesImpl.java:51)
       at android.app.SharedPreferencesImpl$2.run(SharedPreferencesImpl.java:512)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

因为只有魅族 Android 5.1 手机会复现，怀疑是升级魅族 sdk 3.5.0->3.5.1 导致
看堆栈推测是对 SharedPreference 在 getStringSet 或 getAll 两个方法上的使用问题

**Comment by comsince** [comment]
你是在调用pushmanager.clearNotification这个方法复现的吗？

**Comment by comsince** [comment]
麻烦最好说明一下复现场景，我们这边测试还没有找出发现场景，谢谢！

**Comment by hamberluo** [comment]
是 Crashlytics 报上来的，从目前来看应该就是 PushManager.clearNotification(context) 这个方法有这个可能性了

**Comment by asan855** [comment]
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
	at java.util.HashMap$KeyIterator.next(HashMap.java:814)
	at com.android.internal.util.XmlUtils.writeSetXml(XmlUtils.java:350)
	at com.android.internal.util.XmlUtils.writeValueXml(XmlUtils.java:688)
	at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:295)
	at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:264)
	at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:230)
	at com.android.internal.util.XmlUtils.writeMapXml(XmlUtils.java:187)
	at android.app.SharedPreferencesImpl.writeToFile(SharedPreferencesImpl.java:597)
	at android.app.SharedPreferencesImpl.access$800(SharedPreferencesImpl.java:51)
	at android.app.SharedPreferencesImpl$2.run(SharedPreferencesImpl.java:512)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by asan855** [comment]
只会出现在魅族手机上，3.6.0

**Comment by hamberluo** [comment]
这个问题找到根因了

1. 不是因为魅族推送 sdk 造成的
2. 魅族和其他手机如 oppo 都有闪退问题，但只有魅族手机表现为 HashMap 的多线程问题
3. 问题根因是多线程操作了 sp ，理论上来说 sp 是线程安全的，但 5.1 的魅族手机这方面兼容不是很好

结论：只在主线程操作 sp

**Comment by asan855** [comment]
但是sp的操作，都是sdk内部封装的

**Comment by comsince** [comment]
为了避免这个问题，我们下一版本3.6.6将会去除sp的操作

**Comment by hamberluo** [comment]
@asan855 我把我们项目中 sp 操作都改成主线程，就没有这个 crash 了，说明不是 sdk 的问题

**Comment by comsince** [comment]
你把你的sp操作改成主线程执行，是否可能会导致应用ANR

**Comment by hamberluo** [comment]
@comsince sp 本来就是轻量级的存储方式，主线程是不会 ANR 的，除非使用不当（存储大量数据）

**Comment by asan855** [comment]
@hamberluo SDK内部的操作，你如何修改？

**Comment by hamberluo** [comment]
@asan855 内部操作由 sdk 自己修改，而且内部的 sp 和应用层不是一个文件，我们发现排除自己的应用层代码后就没再出现上面的问题

**Comment by comsince** [comment]
3.6.7已经去除相关的sp操作

**Comment by asan855** [comment]
@comsince 看到了，感谢，我们尝试下
