### ISSUE TITLE
3.6.3版本在小米机型上出现兼容性问题

### ISSUE THREAD

**Issue by BinJing** [MEIZUPUSH/PushDemo#22]
问题描述: 已经调用魅族订阅的接口MzSystemUtils.isBrandMeizu(context), 但是还是在小米机型上出现crash

堆栈信息:
java.lang.ClassCastException: Couldn't convert result of type java.lang.String to android.location.Location
	at android.location.LocationManager.getLastKnownLocation()
	at com.meizu.cloud.pushsdk.c.f.e.c(Unknown Source)
	at com.meizu.cloud.pushsdk.a.c.d(Unknown Source)
	at com.meizu.cloud.pushsdk.a.c.a(Unknown Source)
	at com.meizu.cloud.pushsdk.a.c.(Unknown Source)
	at com.meizu.cloud.pushsdk.a.c.(Unknown Source)
	at com.meizu.cloud.pushsdk.a.c$a.a(Unknown Source)
	at com.meizu.cloud.pushsdk.a.a.c(Unknown Source)
	at com.meizu.cloud.pushsdk.a.a.a(Unknown Source)
	at com.meizu.cloud.pushsdk.a.a$1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Back traces end.

**Comment by comsince** [comment]
预计在3.6.7版本修复此问题，敬请关注！

**Comment by BinJing** [comment]
3.6.7版本大概什么时候发布?

**Comment by comsince** [comment]
这个星期应该能发布

**Comment by comsince** [comment]
pushsdk V3.6.7已经解决此问题！
