### ISSUE TITLE
3.6.3版本在联想机型上的适配问题

### ISSUE THREAD

**Issue by SiriusXiao** [MEIZUPUSH/PushDemo#23]
#### 崩溃 堆栈信息：
#0. Crashed: pool-14-thread-1
       at java.lang.Enum.valueOf(Enum.java:182)
       at android.net.wifi.SupplicantState.valueOf(SupplicantState.java:33)
       at android.net.wifi.SupplicantState$1.createFromParcel(SupplicantState.java:255)
       at android.net.wifi.SupplicantState$1.createFromParcel(SupplicantState.java:253)
       at android.net.wifi.WifiInfo$1.createFromParcel(WifiInfo.java:340)
       at android.net.wifi.WifiInfo$1.createFromParcel(WifiInfo.java:325)
       at android.net.wifi.IWifiManager$Stub$Proxy.getConnectionInfo(IWifiManager.java:691)
       at android.net.wifi.WifiManager.getConnectionInfo(WifiManager.java:918)
       at com.meizu.cloud.pushsdk.base.c.b(Unknown Source)
       at com.meizu.cloud.pushsdk.a.c.f(Unknown Source)
       at com.meizu.cloud.pushsdk.a.c.a(Unknown Source)
       at com.meizu.cloud.pushsdk.a.c.(Unknown Source)
       at com.meizu.cloud.pushsdk.a.c.(Unknown Source)
       at com.meizu.cloud.pushsdk.a.c$a.a(Unknown Source)
       at com.meizu.cloud.pushsdk.a.a.c(Unknown Source)
       at com.meizu.cloud.pushsdk.a.a.a(Unknown Source)
       at com.meizu.cloud.pushsdk.a.a$1.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)

--

Fatal Exception: java.lang.NullPointerException: enumType == null || name == null
       at java.lang.Enum.valueOf(Enum.java:182)
       at android.net.wifi.SupplicantState.valueOf(SupplicantState.java:33)
       at android.net.wifi.SupplicantState$1.createFromParcel(SupplicantState.java:255)
       at android.net.wifi.SupplicantState$1.createFromParcel(SupplicantState.java:253)
       at android.net.wifi.WifiInfo$1.createFromParcel(WifiInfo.java:340)
       at android.net.wifi.WifiInfo$1.createFromParcel(WifiInfo.java:325)
       at android.net.wifi.IWifiManager$Stub$Proxy.getConnectionInfo(IWifiManager.java:691)
       at android.net.wifi.WifiManager.getConnectionInfo(WifiManager.java:918)
       at com.meizu.cloud.pushsdk.base.c.b(Unknown Source)
       at com.meizu.cloud.pushsdk.a.c.f(Unknown Source)
       at com.meizu.cloud.pushsdk.a.c.a(Unknown Source)
       at com.meizu.cloud.pushsdk.a.c.(Unknown Source)
       at com.meizu.cloud.pushsdk.a.c.(Unknown Source)
       at com.meizu.cloud.pushsdk.a.c$a.a(Unknown Source)
       at com.meizu.cloud.pushsdk.a.a.c(Unknown Source)
       at com.meizu.cloud.pushsdk.a.a.a(Unknown Source)
       at com.meizu.cloud.pushsdk.a.a$1.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
       at java.lang.Thread.run(Thread.java:856)

**Comment by comsince** [comment]
pushsdk V3.6.7已经解决此问题！
