### ISSUE TITLE
集成魅族推送魅族手机无法收到

### ISSUE THREAD

**Issue by wmhqnyh** [MEIZUPUSH/PushDemo#24]
集成魅族推送魅族手机无法收到，Log信息：

05-03 14:30:30.255 4682-5029/ E/ReflectMethod: invoke
    java.lang.NoSuchMethodException: install [class android.net.SSLSessionCache, class javax.net.ssl.SSLContext]
        at java.lang.Class.getConstructorOrMethod(Class.java:472)
        at java.lang.Class.getMethod(Class.java:857)
        at com.meizu.cloud.pushsdk.base.a.c.a(Unknown Source)
        at com.meizu.cloud.pushsdk.b.h.a.<init>(Unknown Source)
        at com.meizu.cloud.pushsdk.b.c.e.<init>(Unknown Source)
        at com.meizu.cloud.pushsdk.c.b.c$a.<init>(Unknown Source)
        at com.meizu.cloud.pushsdk.c.a.b(Unknown Source)
        at com.meizu.cloud.pushsdk.c.a.a(Unknown Source)
        at com.meizu.cloud.pushsdk.SystemReceiver.onHandleIntent(Unknown Source)
        at com.meizu.cloud.pushsdk.base.IntentReceiver$1.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)

Flyme版本：Flyme OS 4.2.8.2A

**Comment by comsince** [comment]
这个应该不是收不到推送的原因

**Comment by wmhqnyh** [comment]
@comsince 看log信息，感觉是因为反射ReflectMethod: invoke
java.lang.NoSuchMethodException: install [class android.net.SSLSessionCache, class javax.net.ssl.SSLContext]失败的问题使得魅族的推送初始化失败？！

**Comment by comsince** [comment]
难道你调用UpsPushmanager.register 没有返回ups pushid？
或者你试着的在flyme6系统上面测试

**Comment by wmhqnyh** [comment]
@comsince log等打印出ups的pushid，从魅族后台推送也可以检测出正常的推送数量。但就是魅族的这个测试机没办法收到推送的消息，怀疑是因为这个错误使得Flyme的推送初始化失败，而本身的魅族推送集成平台ups是成功的。

**Comment by comsince** [comment]
集成推送请到这里查看：https://github.com/MEIZUPUSH/UpsDemo
上面的错误，不会引起你的应用任何问题，也不会影响推送；

**Comment by wmhqnyh** [comment]
@comsince 感谢您的回复，您发的这个地址有看过，但是暂时没有找到问题的所在。项目是不会出现问题，就是无法接收到推送，其他的测试机都可以收到。这边我再试着找一下吧。再次感谢！

**Comment by wmhqnyh** [comment]
@comsince 在咨询魅族推送的技术客服之后，给的建议是升级Flyme的版本，对于Flyme4的问题，给予的回复是固件问题。

**Comment by comsince** [comment]
有的flyme4版本是有些问题，还是建议使用最新的flyme版本测试，毕竟低版本用户已经很少了

**Comment by wmhqnyh** [comment]
@comsince 再次感谢您的解答！
