### ISSUE TITLE
运行时提示如下 继承的广播接收器not found0

### ISSUE THREAD

**Issue by weiweiForAndroid** [MEIZUPUSH/PushDemo#28]
05-17 20:29:32.640 295-11085/? E/NuPlayer: onScanSources
05-17 20:29:32.643 295-11090/? E/OMXNodeInstance: getParameter(6a:Meizu.MP3, ??(0x7f200406)) ERROR: UnsupportedIndex(0x8000101a)
05-17 20:29:32.669 10982-10982/com.tr E/GinTong: 初始化魅族push
05-17 20:29:32.731 10982-11093/com.tr E/Strategy: isBrandMeizu true
05-17 20:29:33.208 10982-10982/com.tr E/GinTong: com.tr.ui.user.SplashActivity
05-17 20:29:33.208 10982-10982/com.tr E/EBaseActivity: com.tr.ui.user.SplashActivity
05-17 20:29:33.555 10982-10982/com.tr E/[0]:  com.tr.ui.user.SplashActivity@2b82bb75
05-17 20:29:33.556 10982-10982/com.tr E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
05-17 20:29:33.563 274-791/? E/Vold: Failed to find mounted volume for /storage/sdcard1/Android/data/com.tr/files/apk/
05-17 20:29:33.866 10982-11098/com.tr E/GinTong: DXHttpAgent==>sendMessage==>java.net.UnknownHostException: Unable to resolve host "test.online.gintong.com": No address associated with hostname
05-17 20:29:33.867 10982-11098/com.tr E/GinTong: errCode,-1,errMessage :
    errCode,-1,errMessage : 网络不给力...
05-17 20:29:33.867 10982-11098/com.tr E/print_network_status: [-1, ]
05-17 20:29:34.000 10982-11099/com.tr E/GED: Failed to get GED Log Buf, err(0)
05-17 20:29:34.084 851-1508/? E/BluetoothManagerService: getAddress: Return from mName = 魅蓝 note 2
05-17 20:29:34.453 10982-11150/com.tr E/NativeCrypto: ssl=0xdf62e400 cert_verify_callback x509_store_ctx=0xd9789e90 arg=0x0
    ssl=0xdf62e400 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
05-17 20:29:34.696 10982-11163/com.tr E/SystemReceiver: cloud pushService start
05-17 20:29:34.783 10982-11163/com.tr E/QuickTracker: current statics domain is push-statics.meizu.com
05-17 20:29:34.819 10982-10982/com.tr E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
05-17 20:29:34.949 10982-11093/com.tr E/PushTracker->a: pool-8-thread-1|Emitter database empty: 1
05-17 20:29:35.077 11171-11185/? E/art: Failed sending reply to debugger: Broken pipe
05-17 20:29:35.137 10982-11150/com.tr E/NativeCrypto: ssl=0xdf62fe00 cert_verify_callback x509_store_ctx=0xd9789620 arg=0x0
    ssl=0xdf62fe00 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
05-17 20:29:35.246 10982-11150/com.tr E/CellLocation: create GsmCellLocation
05-17 20:29:35.671 11035-11198/com.tr:remote E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
05-17 20:29:35.685 11035-11198/com.tr:remote E/CellLocation: create GsmCellLocation
05-17 20:29:35.916 10982-11166/com.tr E/NativeCrypto: ssl=0xef044800 cert_verify_callback x509_store_ctx=0xd12cc1f0 arg=0x0
05-17 20:29:35.917 10982-11166/com.tr E/NativeCrypto: ssl=0xef044800 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
05-17 20:29:35.952 10982-11093/com.tr E/PushTracker->a: pool-8-thread-1|Emitter database empty: 2
05-17 20:29:36.015 10982-10982/com.tr E/MobclickAgent: onPause called before onResume
05-17 20:29:36.029 10982-10982/com.tr A/MobUncaughtExceptionHandler: Unable to instantiate receiver push.MeiZuPushReceiver: java.lang.ClassNotFoundException: Didn't find class "push.MeiZuPushReceiver" on path: DexPathList[[zip file "/data/app/com.tr-1/base.apk", zip file "/data/app/com.tr-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.tr-1/lib/arm, /vendor/lib, /system/lib]]
    java.lang.RuntimeException: Unable to instantiate receiver push.MeiZuPushReceiver: java.lang.ClassNotFoundException: Didn't find class "push.MeiZuPushReceiver" on path: DexPathList[[zip file "/data/app/com.tr-1/base.apk", zip file "/data/app/com.tr-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.tr-1/lib/arm, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2950)
        at android.app.ActivityThread.access$1800(ActivityThread.java:187)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5869)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "push.MeiZuPushReceiver" on path: DexPathList[[zip file "/data/app/com.tr-1/base.apk", zip file "/data/app/com.tr-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.tr-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.tr-1/lib/arm, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:2945)
        at android.app.ActivityThread.access$1800(ActivityThread.java:187) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5869) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815) 
    	Suppressed: java.lang.ClassNotFoundException: push.MeiZuPushReceiver
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 11 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
05-17 20:29:36.125 295-986/? E/DrmMtkUtil/DrmUtil: checkDcf: not dcf type, dcf version value [80]
05-17 20:29:36.125 295-986/? E/Cta5File: Cta5File::isCta5NormalFile false, bad magic:PK
    Cta5File::isCta5MultimediaFile false, bad magic:
05-17 20:29:36.125 295-986/? E/DrmMtkUtil/DrmUtil: checkDcf: not dcf type, dcf version value [80]
05-17 20:29:36.134 294-294/? E/DrmCtaPlugIn: [ERROR]onOpenDecryptSession - The key is not set by user
05-17 20:29:36.134 294-294/? E/DrmMtkUtil/DrmUtil: parseDcf: not dcf type, dcf version value [80]
05-17 20:29:36.134 294-294/? E/DrmMtkPlugIn: onOpenDecryptSession() : failed to parse dcf file.
05-17 20:29:36.282 295-11237/? E/NuPlayer: onScanSources
05-17 20:29:36.286 295-11246/? E/OMXNodeInstance: getParameter(6b:Meizu.MP3, ??(0x7f200406)) ERROR: UnsupportedIndex(0x8000101a)
05-17 20:29:36.295 11035-11227/com.tr:remote E/NativeCrypto: ssl=0xef041400 cert_verify_callback x509_store_ctx=0xdb947620 arg=0x0
    ssl=0xef041400 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
05-17 20:29:36.328 851-1091/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
05-17 20:29:36.330 851-1091/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
05-17 20:29:36.475 11035-11227/com.tr:remote E/CellLocation: create GsmCellLocation
05-17 20:29:37.143 6473-11279/? E/MzUpdateComponent:2.4.6: ServerManager --> checkUpdateMulti: Illegal Plugin check params ! 
05-17 20:29:37.434 11108-11289/com.tr:pushcore E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
05-17 20:29:37.450 11108-11289/com.tr:pushcore E/CellLocation: create GsmCellLocation
05-17 20:29:37.468 11108-11288/com.tr:pushcore E/NativeCrypto: ssl=0xf4d14600 cert_verify_callback x509_store_ctx=0xdcf96d50 arg=0x0
    ssl=0xf4d14600 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
05-17 20:29:37.525 11108-11108/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
05-17 20:29:37.640 851-1084/? E/BluetoothManagerService: getAddress: Return from mName = 魅蓝 note 2
05-17 20:29:38.497 11171-11303/com.tr:pushservice E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
05-17 20:29:38.519 11171-11303/com.tr:pushservice E/CellLocation: create GsmCellLocation
05-17 20:29:38.544 11171-11302/com.tr:pushservice E/NativeCrypto: ssl=0xf4d14200 cert_verify_callback x509_store_ctx=0xdcd83d50 arg=0x0
    ssl=0xf4d14200 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
05-17 20:29:38.629 11171-11171/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
05-17 20:29:39.591 274-791/? E/Vold: Failed to find mounted volume for /storage/sdcard1/Android/data/com.tr/files/
05-17 20:29:40.035 11251-11314/com.tr E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
05-17 20:29:40.060 11251-11314/com.tr E/CellLocation: create GsmCellLocation
05-17 20:29:40.505 295-987/? E/DrmMtkUtil/DrmUtil: checkDcf: not dcf type, dcf version value [80]
05-17 20:29:40.505 295-987/? E/Cta5File: Cta5File::isCta5NormalFile false, bad magic:PK
    Cta5File::isCta5MultimediaFile false, bad magic:

**Comment by weiweiForAndroid** [comment]
重新发一下log：  


05-17 21:01:47.243 23478-23485/? E/art: Failed sending reply to debugger: Broken pipe
05-17 21:01:49.140 23478-23551/com.tr E/WVMExtractor: Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found
05-17 21:01:49.230 23478-23478/com.tr E/GinTong: 初始化魅族push
05-17 21:01:49.253 23478-23560/com.tr E/Strategy: isBrandMeizu true
05-17 21:01:49.589 23478-23478/com.tr E/GinTong: com.tr.ui.user.SplashActivity
05-17 21:01:49.589 23478-23478/com.tr E/EBaseActivity: com.tr.ui.user.SplashActivity
05-17 21:01:49.771 23478-23478/com.tr E/[0]:  com.tr.ui.user.SplashActivity@3ff69c5
05-17 21:01:49.871 23478-23567/com.tr E/SystemReceiver: cloud pushService start
05-17 21:01:49.881 23478-23567/com.tr E/QuickTracker: current statics domain is push-statics.meizu.com
05-17 21:01:49.967 23478-23560/com.tr E/PushTracker->a: pool-8-thread-1|Emitter database empty: 1
05-17 21:01:50.182 23478-23478/com.tr E/MobUncaughtExceptionHandler: Unable to instantiate receiver push.MeiZuPushReceiver: java.lang.ClassNotFoundException: Didn't find class "push.MeiZuPushReceiver" on path: DexPathList[[zip file "/data/app/com.tr-2/base.apk", zip file "/data/app/com.tr-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.tr-2/lib/arm, /system/fake-libs, /data/app/com.tr-2/base.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
    java.lang.RuntimeException: Unable to instantiate receiver push.MeiZuPushReceiver: java.lang.ClassNotFoundException: Didn't find class "push.MeiZuPushReceiver" on path: DexPathList[[zip file "/data/app/com.tr-2/base.apk", zip file "/data/app/com.tr-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.tr-2/lib/arm, /system/fake-libs, /data/app/com.tr-2/base.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3120)
        at android.app.ActivityThread.-wrap18(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6243)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "push.MeiZuPushReceiver" on path: DexPathList[[zip file "/data/app/com.tr-2/base.apk", zip file "/data/app/com.tr-2/split_lib_dependencies_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_0_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_1_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_2_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_3_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_4_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_5_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_6_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_7_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_8_apk.apk", zip file "/data/app/com.tr-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.tr-2/lib/arm, /system/fake-libs, /data/app/com.tr-2/base.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/com.tr-2/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.handleReceiver(ActivityThread.java:3115)
        	... 8 more
05-17 21:01:50.825 23478-23538/? E/MobclickAgent: onPause called before onResume
05-17 21:01:50.839 23478-23538/? E/MobUncaughtExceptionHandler: Thread starting during runtime shutdown
    java.lang.InternalError: Thread starting during runtime shutdown
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:730)
        at cn.sharesdk.framework.statistics.NewAppReceiver$b.a(Unknown Source)
        at cn.sharesdk.framework.statistics.NewAppReceiver.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
05-17 21:01:50.970 23478-23560/? E/PushTracker->a: pool-8-thread-1|Emitter database empty: 2
05-17 21:01:51.973 23478-23560/? E/PushTracker->a: pool-8-thread-1|Emitter loop stopping: empty limit reached.
05-17 21:01:53.324 2807-2918/? E/WifiConfigManager: getRecentConfiguredNetworks not update current network visibility
05-17 21:01:53.327 2807-2918/? E/WifiStateMachine: mWifiOnScanCount: 9
05-17 21:01:53.445 23478-23500/? E/MobclickAgent: onPause called before onResume
05-17 21:01:53.462 23478-23500/? E/MobUncaughtExceptionHandler: Thread starting during runtime shutdown
    java.lang.InternalError: Thread starting during runtime shutdown
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:730)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1359)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:89)
        at com.baidu.mapapi.http.AsyncHttpClient.get(Unknown Source)
        at com.baidu.platform.base.a.a(Unknown Source)
        at com.baidu.platform.core.b.a.a(Unknown Source)
        at com.baidu.mapapi.search.geocode.GeoCoder.reverseGeoCode(Unknown Source)
        at com.tr.baidumapsdk.BaiduLoc$MyLocationListener.onReceiveLocation(BaiduLoc.java:132)
        at com.baidu.location.LocationClient.callListeners(Unknown Source)
        at com.baidu.location.LocationClient.onNewLocation(Unknown Source)
        at com.baidu.location.LocationClient.access$2800(Unknown Source)
        at com.baidu.location.LocationClient$a.handleMessage(Unknown Source)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)
05-17 21:01:59.882 2807-2890/? E/InputDispatcher: channel '2cdeea9 com.tr/com.tr.ui.user.SplashActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by weiweiForAndroid** [comment]
这个是我的gradle 配置。   
 compile 'com.meizu.flyme.internet:push-internal:3.6.7@aar'

**Comment by comsince** [comment]
这个是receiver是你自己在android manifest里面声明，并且集成meizupushreceiver

**Comment by weiweiForAndroid** [comment]
@comsince  恩，明明清单文件注册了，然后页集成了。不知道为什么总是提示找不到。

**Comment by comsince** [comment]
这个是在调用pushmanger.register出现，还是应用一启动就会出现

**Comment by comsince** [comment]
你是不是采用了插件的方式，还是其他方法，这个可能需要你自己找下问题，正常接入是没有这个问题的

**Comment by weiweiForAndroid** [comment]
@comsince 好的。
