### ISSUE TITLE
运行时报错，（没有采用插件式）

### ISSUE THREAD

**Issue by weiweiForAndroid** [MEIZUPUSH/PushDemo#30]
05-23 13:56:36.201 10107-10107/? E/memtrack: Couldn't load memtrack module (No such file or directory)
05-23 13:56:36.201 10107-10107/? E/android.os.Debug: failed to load memtrack module: -2
05-23 13:56:37.138 10127-10127/? E/memtrack: Couldn't load memtrack module (No such file or directory)
05-23 13:56:37.138 10127-10127/? E/android.os.Debug: failed to load memtrack module: -2
05-23 13:56:45.994 10145-10145/? E/memtrack: Couldn't load memtrack module (No such file or directory)
05-23 13:56:45.994 10145-10145/? E/android.os.Debug: failed to load memtrack module: -2
05-23 13:56:46.625 10162-10162/? E/memtrack: Couldn't load memtrack module (No such file or directory)
05-23 13:56:46.625 10162-10162/? E/android.os.Debug: failed to load memtrack module: -2
05-23 13:56:52.383 10180-10180/? E/memtrack: Couldn't load memtrack module (No such file or directory)
05-23 13:56:52.383 10180-10180/? E/android.os.Debug: failed to load memtrack module: -2
05-23 13:57:03.941 7043-7043/? E/FloatWidget: open
05-23 13:57:04.295 7043-7043/? E/FloatWidget: innerOpen
    refreshContent
05-23 13:57:05.595 10231-10231/? E/memtrack: Couldn't load memtrack module (No such file or directory)
05-23 13:57:05.596 10231-10231/? E/android.os.Debug: failed to load memtrack module: -2
05-23 13:57:05.680 7043-7043/? E/FloatWidget: close
05-23 13:57:05.987 7043-7043/? E/FloatWidget: innerClose
05-23 13:57:06.755 1054-1054/? E/SystemUIMobEventUtils: packageName cannot be null and null-string, or packageName is filter pkg
05-23 13:57:07.970 5371-10273/? E/MzUpdateComponent:2.4.6: ServerManager --> checkUpdateMulti: Illegal Plugin check params ! 
05-23 13:57:08.084 5371-8508/? E/GslbCore: java.io.IOException: Hostname 'servicecut.meizu.com' was not verified
        at com.android.okhttp.Connection.upgradeToTls(Connection.java:205)
        at com.android.okhttp.Connection.connect(Connection.java:155)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:282)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:216)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:391)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:217)
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
        at com.meizu.gslb2.x.a(SourceFile:77)
        at com.meizu.gslb2.t.a(SourceFile:87)
        at com.meizu.gslb2.b$a.a(SourceFile:152)
        at com.meizu.gslb2.b$a.run(SourceFile:191)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
05-23 13:57:08.089 5371-8508/? E/GslbCore: msg:convert api-app.meizu.com form server,throwable:Hostname 'servicecut.meizu.com' was not verified
05-23 13:57:09.014 275-791/? E/Vold: Failed to find mounted volume for /storage/sdcard1/Android/data/com.tr/files/
05-23 13:57:09.232 10248-10248/? E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
05-23 13:57:28.587 275-791/? E/Vold: Failed to find mounted volume for /storage/sdcard1/Android/data/com.meizu.media.video/cache/
05-23 13:57:28.592 275-791/? E/Vold: Failed to find mounted volume for /storage/sdcard1/Android/data/com.meizu.media.video/files/
05-23 13:57:28.810 10283-10318/? E/MzUpdateComponent:2.4.7: Plugin:check interval interrupt
05-23 13:57:28.810 10283-10312/? E/AdLog-Host: update fail: java.lang.Exception: no plugin update info, code=0
05-23 13:57:28.815 10283-10306/? E/SQLiteLog: (283) recovered 8 frames from WAL file /data/data/com.meizu.media.video/databases/statsapp_v3.db-wal
05-23 13:57:28.834 10283-10324/? E/WXSDKEngine: WXEnvironment.sApplication is null
05-23 13:57:28.874 10283-10325/? E/linker: "libweexjsb.so": ignoring 2-entry DT_PREINIT_ARRAY in shared library!
05-23 13:57:29.014 275-791/? E/Vold: Failed to find mounted volume for /storage/sdcard1/Android/data/com.meizu.media.video/cache/
05-23 13:57:29.060 10283-10306/? E/MPlugin: Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
05-23 13:57:29.134 275-791/? E/Vold: Failed to find mounted volume for /storage/sdcard1/Android/data/com.meizu.media.video/cache/
05-23 13:57:29.230 2592-5304/? E/Parcel: Class not found when unmarshalling: com.meizu.cloud.pushsdk.handler.MessageV3
    java.lang.ClassNotFoundException: com.meizu.cloud.pushsdk.handler.MessageV3
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:318)
        at java.lang.Class.forName(Class.java:276)
        at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
        at android.os.Parcel.readParcelable(Parcel.java:2245)
        at android.os.Parcel.readValue(Parcel.java:2152)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
        at android.os.BaseBundle.unparcel(BaseBundle.java:221)
        at android.os.BaseBundle.keySet(BaseBundle.java:321)
        at com.wandoujia.nisdk.core.util.IntentUtil.getExtrasSafe(IntentUtil.java:128)
        at com.wandoujia.nisdk.core.model.converter.SystemNotificationConverter.toIntentPackage(SystemNotificationConverter.java:243)
        at com.wandoujia.nisdk.core.model.converter.SystemNotificationConverter.toPendingIntentPackage(SystemNotificationConverter.java:215)
        at com.wandoujia.nisdk.core.model.converter.SystemNotificationConverter.convert(SystemNotificationConverter.java:49)
        at com.wandoujia.nisdk.core.NIFilter.filter(NIFilter.java:92)
        at com.meizu.notification.NisNotificationFilterImpl.filter(NisNotificationFilterImpl.java:122)
        at com.meizu.notification.FlymeNotificationFilterService$2.interceptNotification(FlymeNotificationFilterService.java:115)
        at meizu.notification.INotificationFilterService$Stub.onTransact(INotificationFilterService.java:57)
        at android.os.Binder.execTransact(Binder.java:454)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.meizu.cloud.pushsdk.handler.MessageV3" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:318) 
        at java.lang.Class.forName(Class.java:276) 
        at android.os.Parcel.readParcelableCreator(Parcel.java:2281) 
        at android.os.Parcel.readParcelable(Parcel.java:2245) 
        at android.os.Parcel.readValue(Parcel.java:2152) 
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2485) 
        at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
        at android.os.BaseBundle.keySet(BaseBundle.java:321) 
        at com.wandoujia.nisdk.core.util.IntentUtil.getExtrasSafe(IntentUtil.java:128) 
        at com.wandoujia.nisdk.core.model.converter.SystemNotificationConverter.toIntentPackage(SystemNotificationConverter.java:243) 
        at com.wandoujia.nisdk.core.model.converter.SystemNotificationConverter.toPendingIntentPackage(SystemNotificationConverter.java:215) 
        at com.wandoujia.nisdk.core.model.converter.SystemNotificationConverter.convert(SystemNotificationConverter.java:49) 
        at com.wandoujia.nisdk.core.NIFilter.filter(NIFilter.java:92) 
        at com.meizu.notification.NisNotificationFilterImpl.filter(NisNotificationFilterImpl.java:122) 
        at com.meizu.notification.FlymeNotificationFilterService$2.interceptNotification(FlymeNotificationFilterService.java:115) 
        at meizu.notification.INotificationFilterService$Stub.onTransact(INotificationFilterService.java:57) 
        at android.os.Binder.execTransact(Binder.java:454) 
    	Suppressed: java.lang.ClassNotFoundException: com.meizu.cloud.pushsdk.handler.MessageV3
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 19 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
05-23 13:57:29.306 302-1128/? E/DrmMtkUtil/DrmUtil: checkDcf: not dcf type, dcf version value [79]
05-23 13:57:29.306 302-1128/? E/Cta5File: Cta5File::isCta5NormalFile false, bad magic:OggS
    Cta5File::isCta5MultimediaFile false, bad magic:$7�����
05-23 13:57:29.306 302-1128/? E/DrmMtkUtil/DrmUtil: checkDcf: not dcf type, dcf version value [79]
05-23 13:57:29.306 302-1128/? E/Cta5File: Cta5File::isCta5NormalFile false, bad magic:OggS
    Cta5File::isCta5MultimediaFile false, bad magic:$7�����'

**Comment by comsince** [comment]
这是系统通知栏的的异常，一般不会影响通知栏弹出，如果你特别在意，你可以升级固件解决
