### ISSUE TITLE
process message error Parcelable encountered IOException reading a Serializable object (name = com.meizu.cloud.pushsdk.platform.message.RegisterStatus)

### ISSUE THREAD

**Issue by crazecoder** [MEIZUPUSH/PushDemo#55]
```
2021-04-12 17:44:52.749 10939-11021/com.whale.im E/PushMessageProxy: process message error Parcelable encountered IOException reading a Serializable object (name = com.meizu.cloud.pushsdk.platform.message.RegisterStatus)
2021-04-12 17:44:58.893 10939-10939/com.whale.im E/@@@@@@@@@@@@@@: fff phone (IBinder)checkService_Method.invoke(null, name):null
2021-04-12 17:44:58.894 10939-10939/com.whale.im E/Shadow: Can't find shadow_server
2021-04-12 17:44:58.895 10939-10939/com.whale.im E/@@@@@@@@@@@@@@: shadow initializeIfNeed：flymemmm
2021-04-12 17:44:58.897 10939-10939/com.whale.im W/System.err: java.lang.Throwable
2021-04-12 17:44:58.897 10939-10939/com.whale.im W/System.err:     at com.meizu.common.shadow.Shadow.<init>(Shadow.java:37)
2021-04-12 17:44:58.897 10939-10939/com.whale.im W/System.err:     at com.meizu.common.shadow.Shadow.<init>(Unknown Source:0)
2021-04-12 17:44:58.897 10939-10939/com.whale.im W/System.err:     at com.meizu.common.shadow.Shadow$Instance.<clinit>(Shadow.java:27)
2021-04-12 17:44:58.898 10939-10939/com.whale.im W/System.err:     at com.meizu.common.shadow.Shadow$Instance.-get0(Unknown Source:0)
2021-04-12 17:44:58.898 10939-10939/com.whale.im W/System.err:     at com.meizu.common.shadow.Shadow.getInstance(Shadow.java:31)
2021-04-12 17:44:58.898 10939-10939/com.whale.im W/System.err:     at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4063)
2021-04-12 17:44:58.898 10939-10939/com.whale.im W/System.err:     at android.app.ActivityThread.-wrap17(Unknown Source:0)
2021-04-12 17:44:58.898 10939-10939/com.whale.im W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1767)
2021-04-12 17:44:58.898 10939-10939/com.whale.im W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2021-04-12 17:44:58.898 10939-10939/com.whale.im W/System.err:     at android.os.Looper.loop(Looper.java:192)
2021-04-12 17:44:58.898 10939-10939/com.whale.im W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6853)
2021-04-12 17:44:58.898 10939-10939/com.whale.im W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-04-12 17:44:58.898 10939-10939/com.whale.im W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
2021-04-12 17:44:58.898 10939-10939/com.whale.im W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
2021-04-12 17:44:58.899 10939-10939/com.whale.im E/@@@@@@@@@@@@@@: shadow collectcollect：AppEvent
2021-04-12 17:44:58.899 10939-10939/com.whale.im E/@@@@@@@@@@@@@@: fff phone (IBinder)checkService_Method.invoke(null, name):null
2021-04-12 17:44:58.900 10939-10939/com.whale.im E/Shadow: Can't find shadow_server
2021-04-12 17:44:58.900 10939-10939/com.whale.im E/@@@@@@@@@@@@@@: shadow mInitialized：false
```

**Comment by crazecoder** [comment]
已解决，混淆问题
