### ISSUE TITLE
注册推送时报空指针错误

### ISSUE THREAD

**Issue by hjgang** [MEIZUPUSH/PushDemo#8]
通过官方demo和文档对比之后，发现区别是我在Application中调用的注册，而demo中是在Activity中调用的。

  Caused by: java.lang.NullPointerException
                                                   at com.meizu.cloud.pushsdk.common.b.h.a(SourceFile:79)
                                                   at com.meizu.cloud.pushsdk.platform.api.PushAPI.<init>(SourceFile:45)
                                                   at com.meizu.cloud.pushsdk.platform.api.PushPlatformManager.<init>(SourceFile:36)
                                                   at com.meizu.cloud.pushsdk.platform.api.PushPlatformManager.getInstance(SourceFile:63)
                                                   at com.meizu.cloud.pushsdk.PushManager.register(SourceFile:140)
                                                   at com.tjzqht.troila.zf.MyApplication.StartMeiZuPush(MyApplication.java:50)
                                                   at com.tjzqht.troila.zf.MyApplication.onCreate(MyApplication.java:44)
                                                   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4379)
                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:141) 
                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272) 
                                                   at android.os.Handler.dispatchMessage(Handler.java:102)

**Comment by JasperXgwang** [comment]
报错信息为测试手机为小米手机，魅族推送平台暂时不支持小米手机

**Comment by comsince** [comment]
这个跟调用位置没有关系！

**Comment by comsince** [comment]
请更新pushsdk至3.2.161219
