### ISSUE TITLE
java.lang.NoSuchMethodError: setVisibility

### ISSUE THREAD

**Issue by CodingMartin** [MEIZUPUSH/PushDemo#9]
```Java 
java.lang.NoSuchMethodError: setVisibility
              at com.meizu.cloud.pushsdk.notification.a.a(SourceFile:141)
              at com.meizu.cloud.pushsdk.notification.a.a(SourceFile:84)
              at com.meizu.cloud.pushsdk.notification.a.c(SourceFile:242)
              at com.meizu.cloud.pushsdk.handler.a.c.a(SourceFile:67)
              at com.meizu.cloud.pushsdk.handler.a.c.a(SourceFile:40)
              at com.meizu.cloud.pushsdk.handler.a.a.b(SourceFile:180)
              at com.meizu.cloud.pushsdk.PushMessageProxy.processMessage(SourceFile:175)
              at com.meizu.cloud.pushsdk.MzPushMessageReceiver.onHandleIntent(SourceFile:40)
              at com.meizu.cloud.pushsdk.common.base.WorkReceiver$1.run(SourceFile:20)
              at android.os.Handler.handleCallback(Handler.java:808)
             at android.os.Handler.dispatchMessage(Handler.java:103)
             at android.os.Looper.loop(Looper.java:193)
             at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by comsince** [comment]
此方法只在api 21 上有效，下一版我们做兼容

**Comment by comsince** [comment]
请问你测试的手机android版本是5.0一下吗？

**Comment by comsince** [comment]
3.3.161226已经解决
